list = ['Tom', 'Jim', 'Sinno']
print(f"Hello, {list.pop()}")
print(f"Hello, {list.pop()}")
print(f"Hello, {list.pop()},you can not come")
list.append("Tony")
print(f"Hello,{list.pop()}")
list.insert(0, "Jam")
list.insert(2, "Aby")
list.append("Aby1")
print(f"Hello, {list.pop()}")
print(f"Hello, {list.pop()}")
print(f"Hello, {list.pop()}")
